#!/usr/bin/expect -f
set timeout -1
spawn scp -o StrictHostKeyChecking=no vps-bot/index.js ubuntu@124.156.202.180:/home/ubuntu/ecosistem-bot/vps-bot/index.js
expect "*?assword:*"
send "Scd-35Q-vJD-BVh\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no ubuntu@124.156.202.180
expect "*?assword:*"
send "Scd-35Q-vJD-BVh\r"
expect "*$*"
send "cd ~/ecosistem-bot/vps-bot\r"
expect "*$*"
send "pm2 restart ecosistem-bot\r"
expect "*$*"
send "pm2 logs ecosistem-bot\r"
interact
